version: "3.0"


volumes:
  redis_1_volume: {}
  redis_2_volume: {}
  redis_3_volume: {}
  redis_4_volume: {}
  redis_5_volume: {}
  redis_6_volume: {}


networks:
  redis_cluster_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.18.0.0/24


services:
# REDIS CLUSTER

  redis_cluster:
    image: 'redis'
    container_name: redis_cluster_init
    command: redis-cli --cluster create \
     173.18.0.11:11001 \
     173.18.0.12:11002 \
     173.18.0.13:11003 \
     173.18.0.14:11004 \
     173.18.0.15:11005 \
     173.18.0.16:11006 \
     --cluster-replicas 1 --cluster-yes
    tty: true
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.0.30
    depends_on:
      - redis_1
      - redis_2
      - redis_3
      - redis_4
      - redis_5
      - redis_6

  redis_1:
    image: 'redis'
    container_name: burrito_redis_1
    ports:
      - "11001"
    volumes:
      - redis_1_volume:/data
      - ./redis/redis_1/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf", "--port 11001" ]
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.0.11

  redis_2:
    image: 'redis'
    container_name: burrito_redis_2
    ports:
      - "11002"
    volumes:
      - redis_2_volume:/data
      - ./redis/redis_2/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf", "--port 11002" ]
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.0.12

  redis_3:
    image: 'redis'
    container_name: burrito_redis_3
    ports:
      - "11003"
    volumes:
      - redis_3_volume:/data
      - ./redis/redis_3/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf", "--port 11003" ]
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.0.13

  redis_4:
    image: 'redis'
    container_name: burrito_redis_4
    ports:
      - "11004"
    volumes:
      - redis_4_volume:/data
      - ./redis/redis_4/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf", "--port 11004" ]
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.0.14

  redis_5:
    image: 'redis'
    container_name: burrito_redis_5
    ports:
      - "11005"
    volumes:
      - redis_5_volume:/data
      - ./redis/redis_5/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf", "--port 11005" ]
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.0.15

  redis_6:
    image: 'redis'
    container_name: burrito_redis_6
    ports:
      - "11006"
    volumes:
      - redis_6_volume:/data
      - ./redis/redis_6/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf", "--port 11006" ]
    networks:
      redis_cluster_net:
        ipv4_address: 173.18.0.16
