version: "3.0"

services:
  burrito_app:
    container_name: burrito_app
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    links:
      - "db"

  db:
    container_name: burrito_db
    image: mysql
    env_file:
      - .env
    ports:
      - "3306:3306"

  redis:
    container_name: burrito_redis
    image: redis
    env_file:
      - .env
    ports:
      - "6379:6379"

  mongo:
    container_name: burrito_mongo
    image: mongo:4.4.6
    ports:
      - "27017:27017"
