version: '1'

services:
  master:
    image: locustio/locust
    env_file:  # LOCUST_LOGIN, LOCUST_PASSWORD, LOCUST_TARGET_HOST
      - ./.env
    ports:
     - "8089:8089"
    volumes:
      - ./tests/locust_main.py:/locust_main.py
    command: -f /locust_main.py --master -H http://master:8089

  worker:
    image: locustio/locust
    env_file:  # LOCUST_LOGIN, LOCUST_PASSWORD, LOCUST_TARGET_HOST
      - ./.env
    volumes:
      - ./tests/locust_main.py:/locust_main.py
    command: -f /locust_main.py --worker --master-host master
