version: "3.0"


services:
# GENERAL SECTION

  nginx:
    container_name: burrito_nginx
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - burrito_about
      - burrito_admin
      - burrito_anon
      - burrito_auth
      - burrito_comments
      - burrito_iofiles
      - burrito_meta
      - burrito_notifications
      - burrito_profile
      - burrito_registration
      - burrito_tickets

  db:
    container_name: burrito_db
    image: mysql
    env_file:
      - .env
    ports:
      - "3306:3306"

  redis:
    container_name: burrito_redis
    image: redis
    ports:
      - "6379:6379"

  mongo:
    container_name: burrito_mongo
    image: mongo:4.4.6
    ports:
      - "27017:27017"

#  prometheus:
#    container_name: burrito_prometheus
#    image: prom/prometheus
#    ports:
#      - 9090:9090
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
#
#  grafana:
#    container_name: burrito_grafana
#    image: grafana/grafana
#    ports:
#      - 3000:3000


# APPS SECTION
# INFO: port forwarding is provided only for testing, this option will be deleted soon

  burrito_about:
    container_name: burrito_about
    build:
      context: .
      dockerfile: burrito/apps/about/Dockerfile
    env_file:
      - .env
    ports:
      - "$BURRITO_PORT"
    links:
      - "db"

  burrito_admin:
    container_name: burrito_admin
    build:
      context: .
      dockerfile: burrito/apps/admin/Dockerfile
    env_file:
      - .env
    ports:
      - "$BURRITO_PORT"
    links:
      - "db"

  burrito_anon:
    container_name: burrito_anon
    build:
      context: .
      dockerfile: burrito/apps/anon/Dockerfile
    env_file:
      - .env
    ports:
      - "$BURRITO_PORT"
    links:
      - "db"

  burrito_auth:
    container_name: burrito_auth
    build:
      context: .
      dockerfile: burrito/apps/auth/Dockerfile
    env_file:
      - .env
    ports:
      - "$BURRITO_PORT"
    links:
      - "db"

  burrito_comments:
    container_name: burrito_comments
    build:
      context: .
      dockerfile: burrito/apps/comments/Dockerfile
    env_file:
      - .env
    ports:
      - "$BURRITO_PORT"
    links:
      - "db"

  burrito_iofiles:
    container_name: burrito_iofiles
    build:
      context: .
      dockerfile: burrito/apps/iofiles/Dockerfile
    env_file:
      - .env
    ports:
      - "$BURRITO_PORT"
    links:
      - "db"

  burrito_meta:
    container_name: burrito_meta
    build:
      context: .
      dockerfile: burrito/apps/meta/Dockerfile
    env_file:
      - .env
    ports:
      - "$BURRITO_PORT"
    links:
      - "db"

  burrito_notifications:
    container_name: burrito_notifications
    build:
      context: .
      dockerfile: burrito/apps/notifications/Dockerfile
    env_file:
      - .env
    ports:
      - "$BURRITO_PORT"
    links:
      - "db"

  burrito_profile:
    container_name: burrito_profile
    build:
      context: .
      dockerfile: burrito/apps/profile/Dockerfile
    env_file:
      - .env
    ports:
      - "$BURRITO_PORT"
    links:
      - "db"

  burrito_registration:
    container_name: burrito_registration
    build:
      context: .
      dockerfile: burrito/apps/registration/Dockerfile
    env_file:
      - .env
    ports:
      - "$BURRITO_PORT"
    links:
      - "db"

  burrito_tickets:
    container_name: burrito_tickets
    build:
      context: .
      dockerfile: burrito/apps/tickets/Dockerfile
    env_file:
      - .env
    ports:
      - "$BURRITO_PORT"
    links:
      - "db"
