version: "4.0"

networks:
  burrito_party:
    name: burrito_party

services:
  db:
    container_name: burrito_db
    image: mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    networks:
      - burrito_party
    environment:
      - LANG=C.UTF_8

  redis:
    container_name: burrito_redis
    image: redis
    env_file:
      - .env
    ports:
      - "6379:6379"
    networks:
      - burrito_party

  mongo:
    container_name: burrito_mongo
    image: mongo:4.4.6
    ports:
      - "27017:27017"
    networks:
      - burrito_party
