version: "3.0"

services:
  burrito_app:
    container_name: burrito_app
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    links:
      - "db"

  db:
    container_name: burrito_db
    image: mysql
    env_file:
      - .env
    ports:
      - "3306:3306"

  redis:
    container_name: burrito_redis
    image: redis
    env_file:
      - .env
    ports:
      - "6379:6379"

#  prometheus:
#    container_name: burrito_prometheus
#    image: prom/prometheus
#    ports:
#      - 9090:9090
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
#
#  grafana:
#    container_name: burrito_grafana
#    image: grafana/grafana
#    ports:
#      - 3000:3000
