[tool.poetry]
name = "Burrito"
version = "0.4.0.dev1"
description = "API for the issue tracker"
authors = ["DimonBor", "m-o-d-e-r"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
aioschedule = "^0.5.2"
anyio = "^3.6.2"
click = "^8.1.3"
distro = "^1.8.0"
fastapi = "^0.95.0"
fastapi-jwt-auth = "^0.5.0"
h11 = "^0.14.0"
idna = "^3.4"
peewee = "^3.16.0"
pydantic = "^1.10.7"
sniffio = "^1.3.0"
starlette = "^0.26.1"
typing-extensions = "^4.5.0"
uvicorn = "^0.21.1"
aioredis = "^2.0.1"
requests = "^2.28.2"
pymysql = "^1.0.3"
cachetools = "^5.3.0"
python-dotenv = "^1.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"