#!/bin/bash

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
RESET='\033[0m'

BURRITO_PATH="$(pwd)/burrito"
EMAIL_TEMPLATES_PATH="$BURRITO_PATH/templates/email"
HTML_EMAILS="$EMAIL_TEMPLATES_PATH/html"
TEXT_EMAILS="$EMAIL_TEMPLATES_PATH/text"

mkdir -p "$TEXT_EMAILS"

echo -e "${BLUE}Converting HTML email templates to plain text...${RESET}"

for email_template in "$HTML_EMAILS"/*.html; do
    new_file_name="$TEXT_EMAILS/$(basename "$email_template" .html).txt"
    echo -e "${YELLOW}$email_template > ${GREEN}$new_file_name${RESET}"
    echo "{# !!! THIS FILE IS GENERATED BY $0 SCRIPT, DO NOT UPDATE IT MANUALLY !!! #}" > $new_file_name
    lynx -dump -nolist -width=1000 "$email_template" >> "$new_file_name"
done

echo -e "${BLUE}Completed${RESET}"
