// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/statistic/general": {
            "post": {
                "description": "get general statistic",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "get general statistic",
                "parameters": [
                    {
                        "description": "GeneralStatisticRequest",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.GeneralStatisticRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GeneralStatisticModel"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.GeneralStatisticModel": {
            "type": "object",
            "properties": {
                "global": {
                    "type": "object",
                    "properties": {
                        "statuses": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.TicketStatusCount"
                            }
                        },
                        "tickets_count": {
                            "type": "integer"
                        }
                    }
                },
                "period": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "date": {
                                "type": "string"
                            },
                            "status_id": {
                                "type": "integer"
                            },
                            "tickets_count": {
                                "type": "integer"
                            }
                        }
                    }
                }
            }
        },
        "models.GeneralStatisticRequest": {
            "type": "object",
            "properties": {
                "from": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                }
            }
        },
        "models.TicketStatusCount": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "status_id": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "BurritoStatistic",
	Description:      "This is an app to provide with a statistic information",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
