name: Burrito microservices to Docker

on:
  push:
    branches: 
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build_containers:    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - about
          - admin
          - anon
          - auth
          - comments
          - iofiles
          - meta
          - notifications
          - profile
          - registration
          - tickets
          - scheduler
          - ws
          - statistic
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Preparing env variables
        run: echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.app }}

      - name: Get short branch name
        id: shortref
        run: |
          RAW_BRANCH="${GITHUB_REF##*/}"
          SAFE_BRANCH="${RAW_BRANCH//[^a-zA-Z0-9._-]/-}"
          echo $RAW_BRANCH
          echo $SAFE_BRANCH
          echo "BRANCH_NAME=${SAFE_BRANCH}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: ./burrito/apps/${{ matrix.app }}/Dockerfile
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ github.ref == 'refs/heads/main' && format('{0}/{1}-${2}:latest', env.REGISTRY, env.IMAGE_NAME, matrix.app) || '' }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PROJECT_BRANCH=${{ steps.shortref.outputs.BRANCH_NAME }}
