name: Burrito microservices to Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build_containers:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - about
          - admin
          - anon
          - auth
          - comments
          - iofiles
          - meta
          - notifications
          - profile
          - registration
          - tickets
          - scheduler
          - ws
          - statistic
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}-${{ matrix.app }}
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        env:
          IMAGE: ${{ env.REGISTRY }}/${{ github.repository }}-${{ matrix.app }}
          TAGS: ${{ steps.meta.outputs.tags }}
        run: |
          echo "Tags to build/push:"
          echo "$TAGS"

          while IFS= read -r TAG; do
            echo "Building $IMAGE:$TAG"
            docker build ./burrito/apps/${{ matrix.app }} -t "$IMAGE:$TAG"
          done <<< "$TAGS"

          while IFS= read -r TAG; do
            echo "Pushing $IMAGE:$TAG"
            docker push "$IMAGE:$TAG"
          done <<< "$TAGS"
